[app]
title = MyApp
package.name = myapp
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3, PySide6
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.0.0
fullscreen = 0
android.permissions = INTERNET
android.api = 30
android.minapi = 21
android.ndk = 23b
android.sdk = 33
p4a.branch = develop
android.arch = arm64-v8a
