name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 \
            cmake cython3

      - name: Setup Android SDK/NDK
        run: |
          mkdir -p /home/runner
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /home/runner/android-sdk
          mv /home/runner/android-sdk/cmdline-tools /home/runner/android-sdk/latest
          mkdir -p /home/runner/android-sdk/platform-tools
          
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d /home/runner
          mv /home/runner/android-ndk-r25c /home/runner/android-ndk-r25c

          echo "export ANDROID_SDK_ROOT=/home/runner/android-sdk" >> $GITHUB_ENV
          echo "export ANDROID_NDK_HOME=/home/runner/android-ndk-r25c" >> $GITHUB_ENV

      - name: Install Buildozer
        run: |
          pip install --upgrade pip wheel
          pip install buildozer cython==0.29.36

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug deploy

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp.apk
          path: ./bin/*.apk
