name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 \
            cmake cython3 coreutils  # Добавляем coreutils для yes

      - name: Setup Android SDK/NDK
        run: |
          # Установка Android SDK с правильной структурой
          mkdir -p /home/runner/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /home/runner/android-sdk/cmdline-tools
          mv /home/runner/android-sdk/cmdline-tools/cmdline-tools /home/runner/android-sdk/cmdline-tools/latest

          # Установка Android NDK
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d /home/runner

          # Настройка переменных окружения
          echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=/home/runner/android-ndk-r25c" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

          # Проверка доступности sdkmanager
          which sdkmanager

          # Принятие лицензий (без yes)
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          echo -e "\n\n\n\n\n\n\n\n\n\n" | sdkmanager --licenses > /dev/null 2>&1

      - name: Install Buildozer
        run: |
          pip install --upgrade pip wheel
          pip install buildozer cython==0.29.36

      - name: Initialize Buildozer
        run: |
          buildozer init
          sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec

      - name: Clean previous builds
        run: |
          rm -rf .buildozer
          mkdir -p .buildozer

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp.apk
          path: ./bin/*.apk
